#ifndef CONSTANTES_H_INCLUDED
#define CONSTANTES_H_INCLUDED

#define TAM_VENTANA_X 600
#define TAM_VENTANA_Y 600

#define TAM_CULEBRA 15
#define TAM_CUADRO 4

#endif // CONSTANTES_H_INCLUDED
